### ISSUE TITLE
Client state display UI is broken

### ISSUE THREAD

**Issue by mxmilkiib** [linuxaudio/new-session-manager#18]
![image](https://user-images.githubusercontent.com/108225/85076707-916a8f00-b1b8-11ea-8895-d5c571ee8938.png)
vs.
![image](https://user-images.githubusercontent.com/108225/85076746-b101b780-b1b8-11ea-89be-358d897d9b54.png)

**Comment by falkTX** [comment]
you mean the color outline?

**Comment by mxmilkiib** [comment]
Where it says "ready" and yes the colour outline.

**Comment by falkTX** [comment]
Fixed in latest 2 commits.

![Screenshot_20200630_111955](https://user-images.githubusercontent.com/1334853/86115288-a9e57e00-bac3-11ea-9e1b-2fbd05994c37.png)

I can't seem to find a way to draw the outline color though, could be NTK specific?
Anyway, it is only a small additional visual clue, we can still read/see the status text
