### ISSUE TITLE
qmidiarp dies in NSM

### ISSUE THREAD

**Issue by grammoboy2** [linuxaudio/new-session-manager#61]
fyi
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=976138

**Comment by falkTX** [comment]
Please stop reporting bugs against NSM of what are actually external application bugs.
Idea might be good, but it does not really contribute to the session manager project.

If there is a specific question, sure, open a ticket or something to get more details.
But a broken application has nothing to do with a protocol/spec, the bug is in the application, not with the protocol.
