### ISSUE TITLE
NSM_SESSION_ROOT evar?

### ISSUE THREAD

**Issue by mxmilkiib** [linuxaudio/new-session-manager#66]
It would be handy to have a NSM_SESSION_ROOT path environment variable that can point to a custom session root directory for NSM control apps to use (if no argument for one is provided).

**Comment by diovudau** [comment]
Thanks. A sensible request in line with https://github.com/linuxaudio/new-session-manager/issues/15 and general Linux practices. 
We will have to see if that is already covered by using the XDG environment variables, or if that is too generic. 
I'm closing the comment because this will be worked on in the issue above as well. For the resulting work it is therefore redundant, even if the aspect is new.
