### ISSUE TITLE
Sessions in a hidden folder?

### ISSUE THREAD

**Issue by grammoboy2** [linuxaudio/new-session-manager#69]
Is this  a good idea? Putting linuxaudio sessions in ~/.local/share/* in this case ~/.local/share/nsm/ ?

Do you expect ardour users to save their ardour sessions in ~/.local/share/ardour/ ?

**Comment by falkTX** [comment]
that is a good question.

it is the default location, can be overridden by a environment variable.
worth noting perhaps, ladish does the same, but not in a XDG dir.

I think we should add an option in the NSM GUIs to open the session folder. in case the user wants to manually inspect them, for any reason.

**Comment by grammoboy2** [comment]
I wonder if I'll get a message from libreoffice soon, that I need to symlink my ~/Documents to ~/.local/share/libreoffice/documents/
I hope they won't sent it any time soon. 
You suggest to add something to the GUI, but if you keep it as it is, you don't need to add anything. It should solve or improve something to justify such a change right? Without it, it's looks to like it is just for the sake of showing ones love for conventions. 
The original GUI is not written to do everything from the GUI, one can disagree with this, but it is as it is and moving the sessions folders to a multi-layered hidden folder, won't make it easier to work with for at least a part of the NSM users I can imagine.

**Comment by diovudau** [comment]
See #15.

Yes, this will happen. If it works for Steam, it will work for us. Convenience solutions are obvious and do not need to be suggested at the moment.

**Comment by grammoboy2** [comment]
I think it's a bad idea and it's bad to assume 'convenience solutions' whatever that is, as good by default without thinking, very questionable at least, because there are fair arguments against it I think.  

I'm not a XDG expert, but I really doubt whether this applies to the NSM situation and if our beloved pulseaudio developer had this case in mind when he co-wrote that document. 

These bugs refer to config files for instance https://bugs.documentfoundation.org/show_bug.cgi?id=32263
They don't tell the applications that project files, like documents should be in a hidden folder. Why would that make sense?
Qtractor, Ardour files session files in a hidden folder? This must be a total wrong interpretation of XDG in the context of NSM. 
You think Steam is a good comparison to NSM?

I can imagine this can become tricky for backups too. A ignorant user looks at his home folder to see what he wants to backup. He won't see the NSM Sessions folder...

**Comment by diovudau** [comment]
Original issue #15 is over half a year old now. I am not going to answer on this one anymore. You are projecting your own fears onto hypothetical users.  You can say "I am uncomfortable with this change for my workflow" but don't hide behind "users" to strengthen your argument.

**Comment by grammoboy2** [comment]
It has nothing to do with fears, please don't put words in my mouth.  How old a issue is, is not a very strong argument either.

It's a wrong interpretation of the XDG guidelines and if you do think it's not, you've to explain it.

**Comment by dvzrv** [comment]
> I can imagine this can become tricky for backups too. A ignorant user looks at his home folder to see what he wants to backup. He won't see the NSM Sessions folder...

Making assumptions about how users use their systems does not necessarily help your point across (there are - to my knowledge - no user or usability studies for this software).
To turn the argument around with opposite hypotheses:
A user might not even go looking for files but only work with the GUI. 
A user might use backup software that breaks on the white space in `~/NSM Sessions/`.
A user might want to change the location of the directory.

If anything the XDG specification helps in solving a user's need to e.g. have an easy way of identifying locations to backup (because it is standardized).

> I'm not a XDG expert, but I really doubt whether this applies to the NSM situation and if our beloved pulseaudio developer had this case in mind when he co-wrote that document.

The XDG specifications were created to be flexible enough for users (or desktop environments for that matter) to move things to different locations (with the help of environment variables) based on requirement. It is not relevant who developed or co-authored the specification as long as it is useful.
If you state to not be an expert, how can you claim that it is used wrongly? You will need to back up your claims with facts.

That being said: It is not always preferable to cook one's own soup (as in: it is absolutely fine to rely on standards/ specifications). Making use of the XDG specification is a good example of just that.

**Comment by diovudau** [comment]
To be totally clear. This discussion is locked because there was already an issue for that and no need to open a new one from the beginning: #15
